/*
/*
Fase 2 : 07/11/2022
1-Jframe dar de alta un@ peluquer@, modificar, Borrar
2-JFrame poner precios servicios
3- Abouty mas
*/

package MRodriguez;

import java.awt.Color;
import java.awt.Dimension;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;


/**
 *
 * @author josemonpes
 */
public class JFrameMain2 extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain2() {
        initComponents();
        initConfig();
    }

    private void initConfig() {
        
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //Factor de forma
        int FF = 80;
        int screenHeigth = (int) screenSize.getHeight();
        int screenWidth = (int) screenSize.getWidth();

        this.setSize(screenWidth * FF / 100, screenHeigth * FF / 100);
        this.setLocationRelativeTo(getComponentAt(screenWidth * FF / 100, screenHeigth * FF / 100));

        //Ponemos el panel centrado en el medio de la ventana
        int panelX = (getWidth() - jPanel1.getWidth() - getInsets().left - getInsets().right) / 2;
        int panelY = ((getHeight() - jPanel1.getHeight() - getInsets().top - getInsets().bottom) / 2);

        jPanel1.setLocation(panelX, panelY);
        getContentPane().setBackground(new Color(133, 47, 178));

//        getContentPane().setBackground(new Color(190, 140, 217));
        this.setLocationRelativeTo(this);

        jPanel1.setBackground(new Color(190, 140, 217));
    }
    
     private void functionCRUD(String Control) throws MalformedURLException, IOException {
        String phpFileName="controllerDB.php";
        String path= "http://localhost/M13/P1/";
        String Login = jTextFieldUser.getText(),Password=jTextFieldPassword.getText(), Email=jTextFieldPassword.getText();
        String query="";
            query+= "?Control="+Control;
            query+= "&D01="+Login;
            query+= "&D02="+Password;
            query+= "&D03="+Email;
            
        String urlLink = path+phpFileName+query;
        URL url = new URL(urlLink); 
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("GET");
        
        BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()));
        StringBuffer sb = new StringBuffer();
        String line;
        while ((line = in.readLine()) !=null) {            
            sb.append(line);
                    System.out.println(line);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextFieldMailAdm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPasswordAdm = new javax.swing.JTextField();
        jTextFieldUserAdm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("User");

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Users ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 20, 140, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("User");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 60, 80, 30);

        jTextFieldUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldUser);
        jTextFieldUser.setBounds(190, 60, 350, 31);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 100, 80, 30);

        jTextFieldPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldPassword);
        jTextFieldPassword.setBounds(190, 100, 350, 31);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Mail");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 140, 80, 30);

        jTextFieldMail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldMail);
        jTextFieldMail.setBounds(190, 140, 350, 31);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 200, 110, 23);

        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(192, 200, 110, 23);

        jButton3.setText("Modificate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(310, 200, 110, 23);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(430, 440, 110, 23);

        jButton7.setText("Modificate");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(300, 440, 120, 23);

        jButton8.setText("Register");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(190, 440, 100, 23);

        jTextFieldMailAdm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldMailAdm);
        jTextFieldMailAdm.setBounds(190, 380, 350, 31);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Mail");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(140, 380, 80, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 340, 80, 30);

        jTextFieldPasswordAdm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldPasswordAdm);
        jTextFieldPasswordAdm.setBounds(190, 340, 350, 31);

        jTextFieldUserAdm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldUserAdm);
        jTextFieldUserAdm.setBounds(190, 300, 350, 31);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("User");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(140, 300, 80, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Administrador");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(300, 260, 140, 30);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MRodriguez/Resources/atras.png"))); // NOI18N
        jButton9.setText("BACK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(560, 230, 170, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 20, 770, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String Control="Delete";
       String password= jTextFieldPassword.getText();
       String email= jTextFieldMail.getText();
       String user= jTextFieldUser.getText();
        try {
            ClassConnection.functionCRUD(Control, password,email,user);
        } catch (IOException ex) {
          
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String Control="Update";
       String password= jTextFieldPassword.getText();
       String email= jTextFieldMail.getText();
       String user= jTextFieldUser.getText();
        try {
            ClassConnection.functionCRUD(Control, password,email,user);
        } catch (IOException ex) {
          
        }    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String Control="Create";
       String password= jTextFieldPassword.getText();
       String email= jTextFieldMail.getText();
       String user= jTextFieldUser.getText();
        try {
            ClassConnection.functionCRUD(Control, password,email,user);
        } catch (IOException ex) {
          
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String Control="Delete2";
       String password= jTextFieldPasswordAdm.getText();
       String email= jTextFieldMailAdm.getText();
       String user= jTextFieldUserAdm.getText();
        try {
            ClassConnection.functionCRUD(Control, password,email,user);
        } catch (IOException ex) {
          
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String Control="Update2";
       String password= jTextFieldPasswordAdm.getText();
       String email= jTextFieldMailAdm.getText();
       String user= jTextFieldUserAdm.getText();
        try {
            ClassConnection.functionCRUD(Control, password,email,user);
        } catch (IOException ex) {
          
        }    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       String Control="Create2";
       String password= jTextFieldPasswordAdm.getText();
       String email= jTextFieldMailAdm.getText();
       String user= jTextFieldUserAdm.getText();
        try {
            ClassConnection.functionCRUD(Control, password,email,user);
        } catch (IOException ex) {
          
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        DataClass.gotoAnotherJFrame(this,DataClass.JF4);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldMailAdm;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldPasswordAdm;
    private javax.swing.JTextField jTextFieldUser;
    private javax.swing.JTextField jTextFieldUserAdm;
    // End of variables declaration//GEN-END:variables

    
}
